dist: trusty
language: node_js
node_js:
  - 13
deploy:
  provider: npm
  email: novikovio74@gmail.com
  skip_cleanup: true
  tag: latest
  on:
    branch: master
    repo: Hooked74/project-tools
  api_key:
    secure: fi2h5+1aYAIQ4mWJK1b/YUsTGsDBkuYSLpm+s4qF8gCFKQDQ5kCjLLI8fCAXhAVaE4QIgrj+uByfJ82/zsrxPMVzW+iOCNjHppnyaXHW1I3jjg2UOBs0gedkh67G/LxWPsCyTQ3O8g1U+pA5Bzqaxlr/auijgpJVV1Pz+8FDS0c4j5OX49jHkEqwixLG2pJ8OHTR6olRIt4V3rqiCTEn4eXf3AFwkz6ch4VDV24RpRqwrw2/1pvkWEeVbx4sr+KIPwRt3cwfIt7sg7bP5RFWUzykFxp9HkPcADo1odUUCNHJgDjKa98nDc2wHAsCIVAnpRkylWSIDQPOZZ9tKZipSLr4iVwvxdbP9Jwl5Ek6KT37ICr7YrmH++ka+5fZRYff/9fDKLVWdACKE/D3fVOuXcsCIikzM14s3CGhcIVkiboGMJJMMu21+U6dOd9PWVCGXVxmgrUtOzUVA0lrdKa+SK4r3mEq44dHtGdhGv3tGq2/oC1/1FP9DM5YVLokDfBCkvoYvJHQc6M/9SXTrep69NVYxeDT3o8PoDLpdyw/xuLTHnkGw4LEDslm4yWV2cCal040e6XIwJ7X0ghDw8zcRVSL/XGTpu3u2h4A5SgmmCG9EHOIB49e1Nt7vNQkiP/KV708kE40EX2QPtnjb86kUGuF9oFqKk3LXK/uY5WWFMw=
