dist: trusty
language: node_js
node_js:
  - 12
deploy:
  provider: npm
  email: novikovio74@gmail.com
  skip_cleanup: true
  tag: latest
  on:
    branch: master
    repo: Hooked74/project-tools
  api_key:
    secure: Ys/qBM2aFH/1VFEYEo+J3dBTt8Xm41TwBk5Vyt1kl9EAJ+DO7QBA0tTA5AE5ZVS5vQFm3xPF/2lS9LKf66743avBhUhxTwboA2bW38pGwDJSJ+srOa/5o1HpQrFGuRw4WFuGIFZ5WqWbRpeOmcx8+ZfIxloForPBEPXREb8I1+FQV6luqGyWIW8lnMcTTNieA9m2EIc8BVEc3f66I4Ar2ORYnnlNPWzVFRO4lEtfwaqSrVhagwOx8BVmQrysixo2eB9+wp6NB+cmZBc9IXUa6E6KIZ2hyujs0ekbSenYIaGVAbA/dbJr18y1BE7MMVpHDK86Dj7APSz826ZN+Nvspc4ewFuYN27iFzCcOcq0BgsMcQvf2GiB5pAV93H8tYSnJ3gh9KByF5dhaMKftdR5Td0/UgKm/0Fxez8W0avbPIQbZrdRHQbbUsGwsuBkSiwD5ctcLSA9RShLvISCk84eQW4BfnfdZUiHEenWNkbWv31WvdLKY3rQC5+lCYfc4TPu+RyE8l6+vMtOdXvuoA1W8zJHMbxoDInCwJdl9/f//GCeroMnRujGY4nso7Tuy8YydATX4PSAjur7fm5c9DWVt0SlQgHS2uxrA0NCVwEN+0gN1od9E+wMF1Gf6OmQyvMTujSm89Zf5AexfggQg17Gj2u3aIucgyNSwrZGcDwfr7w=
